"""add date to the stages

Revision ID: 05dfd81ea14e
Revises: 3d31858e5d99
Create Date: 2021-10-04 15:35:40.196332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05dfd81ea14e'
down_revision = '3d31858e5d99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stages', sa.Column('date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stages', 'date')
    # ### end Alembic commands ###
