"""race logic update

Revision ID: 10ee3e1bb422
Revises: 557df8874f73
Create Date: 2021-09-24 10:51:30.571603

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '10ee3e1bb422'
down_revision = '557df8874f73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('athelete_stage')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('athelete_stage',
    sa.Column('athlete_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('stage_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], name='athelete_stage_ibfk_1'),
    sa.ForeignKeyConstraint(['stage_id'], ['stages.id'], name='athelete_stage_ibfk_2'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
