"""add relationships into the athlete comp class

Revision ID: 19b0c4c731f9
Revises: b796309efa7f
Create Date: 2021-09-24 10:23:40.027622

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '19b0c4c731f9'
down_revision = 'b796309efa7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('races',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=True),
    sa.Column('stage_id', sa.Integer(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('time', sa.Time(), nullable=True),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ),
    sa.ForeignKeyConstraint(['stage_id'], ['stages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('athlete_stage')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('athlete_stage',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('athlete_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('stage_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rank', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('time', mysql.TIME(), nullable=True),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], name='athlete_stage_ibfk_1'),
    sa.ForeignKeyConstraint(['stage_id'], ['stages.id'], name='athlete_stage_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('races')
    # ### end Alembic commands ###
