"""add email column to the athletes

Revision ID: 1e9f5fe4f009
Revises: 475910fe92e5
Create Date: 2021-09-06 14:06:54.229908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e9f5fe4f009'
down_revision = '475910fe92e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('athletes', sa.Column('email', sa.String(length=120), nullable=False))
    op.create_unique_constraint(None, 'athletes', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'athletes', type_='unique')
    op.drop_column('athletes', 'email')
    # ### end Alembic commands ###
