"""remove si uniqueness

Revision ID: 24fd5d643c0a
Revises: faf7e96f830e
Create Date: 2021-09-09 14:44:50.080446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24fd5d643c0a'
down_revision = 'faf7e96f830e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('si', table_name='athletes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('si', 'athletes', ['si'], unique=False)
    # ### end Alembic commands ###
