"""some changes in athlete stage relationship

Revision ID: 2a9f59d284e6
Revises: 3d056320e427
Create Date: 2021-09-23 14:15:33.775905

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2a9f59d284e6'
down_revision = '3d056320e427'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('athlete_stage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=True),
    sa.Column('stage_id', sa.Integer(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('time', sa.Time(), nullable=True),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ),
    sa.ForeignKeyConstraint(['stage_id'], ['stages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('athelete_comp')
    op.add_column('stages', sa.Column('length', sa.Float(), nullable=False))
    op.add_column('stages', sa.Column('controls', sa.Integer(), nullable=False))
    op.drop_index('name', table_name='stages')
    op.drop_index('short_name', table_name='stages')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('short_name', 'stages', ['short_name'], unique=False)
    op.create_index('name', 'stages', ['name'], unique=False)
    op.drop_column('stages', 'controls')
    op.drop_column('stages', 'length')
    op.create_table('athelete_comp',
    sa.Column('athlete_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('competition_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], name='athelete_comp_ibfk_1'),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], name='athelete_comp_ibfk_2'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('athlete_stage')
    # ### end Alembic commands ###
