"""user update

Revision ID: 384a5fd7deb7
Revises: d2f49383b489
Create Date: 2021-09-02 14:40:45.322330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '384a5fd7deb7'
down_revision = 'd2f49383b489'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_director', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_director')
    # ### end Alembic commands ###
