"""add-back si uniqueness

Revision ID: 3d056320e427
Revises: 24fd5d643c0a
Create Date: 2021-09-09 14:51:39.945873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d056320e427'
down_revision = '24fd5d643c0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'athletes', ['si'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'athletes', type_='unique')
    # ### end Alembic commands ###
