"""turn into the beginnihg

Revision ID: 3d31858e5d99
Revises: 4320081fe4f7
Create Date: 2021-09-30 11:44:07.575126

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3d31858e5d99'
down_revision = '4320081fe4f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stage_athlete')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stage_athlete',
    sa.Column('stage_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('athlete_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], name='stage_athlete_ibfk_1'),
    sa.ForeignKeyConstraint(['stage_id'], ['stages.id'], name='stage_athlete_ibfk_2'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
