"""race logic update

Revision ID: 4dbcd1f03dd2
Revises: 19b0c4c731f9
Create Date: 2021-09-24 10:36:17.497449

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4dbcd1f03dd2'
down_revision = '19b0c4c731f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('athelete_stage')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('athelete_stage',
    sa.Column('athlete_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('stage_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], name='athelete_stage_ibfk_1'),
    sa.ForeignKeyConstraint(['stage_id'], ['stages.id'], name='athelete_stage_ibfk_2'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
