"""race logic update

Revision ID: 557df8874f73
Revises: 4dbcd1f03dd2
Create Date: 2021-09-24 10:42:25.387737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '557df8874f73'
down_revision = '4dbcd1f03dd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('athelete_stage',
    sa.Column('athlete_id', sa.Integer(), nullable=True),
    sa.Column('stage_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ),
    sa.ForeignKeyConstraint(['stage_id'], ['stages.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('athelete_stage')
    # ### end Alembic commands ###
