"""turn original

Revision ID: 5ec7b1e804ed
Revises: 0c0b50dbb87d
Create Date: 2021-09-29 14:40:21.133336

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5ec7b1e804ed'
down_revision = '0c0b50dbb87d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stage_athlete')
    op.add_column('results', sa.Column('athlete_id', sa.Integer(), nullable=True))
    op.add_column('results', sa.Column('stage_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'results', 'stages', ['stage_id'], ['id'])
    op.create_foreign_key(None, 'results', 'athletes', ['athlete_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'results', type_='foreignkey')
    op.drop_constraint(None, 'results', type_='foreignkey')
    op.drop_column('results', 'stage_id')
    op.drop_column('results', 'athlete_id')
    op.create_table('stage_athlete',
    sa.Column('stage_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('athlete_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('result_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], name='stage_athlete_ibfk_1'),
    sa.ForeignKeyConstraint(['result_id'], ['results.id'], name='stage_athlete_ibfk_2'),
    sa.ForeignKeyConstraint(['stage_id'], ['stages.id'], name='stage_athlete_ibfk_3'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
