"""add viewonly logic and add primary key to assocation table

Revision ID: a156590c7a21
Revises: 5ec7b1e804ed
Create Date: 2021-09-29 15:24:35.109344

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a156590c7a21'
down_revision = '5ec7b1e804ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('results', 'athlete_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('results', 'stage_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('results', 'stage_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('results', 'athlete_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
