"""add relationships into the athlete comp class

Revision ID: b796309efa7f
Revises: 2a9f59d284e6
Create Date: 2021-09-24 10:20:16.677205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b796309efa7f'
down_revision = '2a9f59d284e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('athelete_stage',
    sa.Column('athlete_id', sa.Integer(), nullable=True),
    sa.Column('stage_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ),
    sa.ForeignKeyConstraint(['stage_id'], ['stages.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('athelete_stage')
    # ### end Alembic commands ###
