"""club stage comp relation update

Revision ID: d93f00fdc2e3
Revises: 939df4e19024
Create Date: 2021-09-24 12:14:58.749337

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd93f00fdc2e3'
down_revision = '939df4e19024'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('club_stage',
    sa.Column('club_id', sa.Integer(), nullable=True),
    sa.Column('stage_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ),
    sa.ForeignKeyConstraint(['stage_id'], ['stages.id'], )
    )
    op.drop_table('club_comp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('club_comp',
    sa.Column('club_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('competition_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], name='club_comp_ibfk_1'),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], name='club_comp_ibfk_2'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('club_stage')
    # ### end Alembic commands ###
