"""club update

Revision ID: faf7e96f830e
Revises: 1e9f5fe4f009
Create Date: 2021-09-08 16:14:52.115734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'faf7e96f830e'
down_revision = '1e9f5fe4f009'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('city', table_name='clubs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('city', 'clubs', ['city'], unique=False)
    # ### end Alembic commands ###
